export const FETCH_ATTRIBUTE_NAMES = 'FETCH_ATTRIBUTE_NAMES';
export const FETCH_PRIMARY_SKILLS = 'FETCH_PRIMARY_SKILLS';
export const FETCH_SECONDARY_SKILLS = 'FETCH_SECONDARY_SKILLS';
export const FETCH_ARCHETYPE_DATA = 'FETCH_ARCHETYPE_DATA';
export const FETCH_BUILD_DATA = 'FETCH_BUILD_DATA';
